### ISSUE TITLE
Clients that are NATed

### ISSUE THREAD

**Issue by joeblew99** [masipcat/wireguard-go-docker#1]
Wondering is NATed clients can use this to find each others IP addresses ?

I have a situation where i need to connect users that are all on Mobiles and Desktops and so are NATed.

**Comment by masipcat** [comment]
You can use wireguard (or any vpn) to connect all devices that are behind a NAT in the same (virtual) network (as long as the VPN server is accessible from the internet by all peers).

> Wondering is NATed clients can use this to find each others IP addresses ?

I'm not sure what do you mean...  In the case of wireguard, you'll assign a private static IP (10.x.x.x) to each peer. Your `wg0.conf` in your server would be something like:

```
[Interface]
Address = 10.33.0.1/24
ListenPort = 51820
PostUp = wg set wg0 private-key /etc/wireguard/privatekey && iptables -t nat -A POSTROUTING -s 10.33.0.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Desktop 1
[Peer]
PublicKey = ...
AllowedIPs = 10.33.0.2/32

# Desktop 2
[Peer]
PublicKey = ...
AllowedIPs = 10.33.0.3/32

# Mobile 1
[Peer]
PublicKey = ...
AllowedIPs = 10.33.0.4/32
```

I hope I've answered your question!

**Comment by joeblew99** [comment]
Thanks for the answer.

I think it looks like it will work from the example you have.

Just to be sure here's a use case.

5 sites.
None have a public static IP and are behind symmetric routers. So NAT punch
through using webrtc etc won't work without using a full proxy relay hence
defeating the purpose.

The cloud proxy knows all users in each sites user auth key.

Site A , user 1 wants to connect with site B, user 2 and so initiates a
call to that user via the cloud proxy.

The cloud proxy probably does an auth check and let's the two communicate
doing whatever wireguard goes for session initiation.

The data between the users is encrypted such that the cloud proxy cannot
eaves drop !

This is for a secure messaging system btw.
If any user is not online and when they do come online each party is told
so that messages will then be forwarded.

For wake-up on a mobile we will probably use standard Girish from appleboy.
It's written in golang

Thanks ..

**Comment by masipcat** [comment]
I think this would work but if you only need the vpn to make WebRTC work, maybe using a 'webrtc hub' like https://jitsi.org/jitsi-videobridge/ would do it better.
