### ISSUE TITLE
Readme - bug

### ISSUE THREAD

**Issue by bigcookie** [masipcat/wireguard-go-docker#18]
This section to generate keys:
# Generate publickey from privatekey
docker run --rm -i masipcat/wireguard-go wg genkey < privatekey > publickey

should be
# Generate publickey from privatekey
docker run --rm -i masipcat/wireguard-go wg **pub**key < privatekey > publickey

**Comment by masipcat** [comment]
Sorry, I forgot about this issue. Now is fixed by @wnienhaus
