### ISSUE TITLE
Fix from  #21 not in latest image

### ISSUE THREAD

**Issue by Eldiabolo21** [masipcat/wireguard-go-docker#28]
Hey there, 

I was pulling my hair out, because I was using the latest tag from docker hub and I ran into the issue fixed in  #21. 
Turns out, the latest image has not been updated, only the `0.0.20220316`  Tag has the fix. 

Is this intentional or an oversight?

**Comment by masipcat** [comment]
Sorry, it was not intentional. Now it's fixed!
