### ISSUE TITLE
Update to new wireguard-tools repo

### ISSUE THREAD

**Issue by bladeswords** [masipcat/wireguard-go-docker#3]
Just noticed that this image appears to use the wireguard repo to build only the tools.  It appears like the repo has been split and the tools now live in their own repo.

https://git.zx2c4.com/wireguard-tools/

I haven't tested updating this in the Dockerfile as of yet, hopefully you get to it before me.

Thanks for the project :)

**Comment by masipcat** [comment]
Oh, I didn't know. I'll try to take a look during the weekend.

Thank you :-)

**Comment by masipcat** [comment]
Done in commit 0b9145de7625e2cac00bbb742ec656d59eea0830
