### ISSUE TITLE
Again, Fix from #21 not in latest image 

### ISSUE THREAD

**Issue by Eldiabolo21** [masipcat/wireguard-go-docker#32]
Hello again, 

I just pulled more of my hair out, after running into the same issue again as I had in #28 

The latest tag on Dockerhub does not contain the latest image. I dont know which version it is, but it still has the bug where the shutdown trap doesnt work and iptables rules and wg the interface arent removed. 

Can be spotted by hashes too. Latest  hash for amd64 0707ec5c87ed. for 0.0.20230223 hash is[9b8681b459a3. 

Is really appreciate your work, but please fix your release deployment. 

thanks!

**Comment by masipcat** [comment]
Hello,

Now the build process uses docker buildx and it's automated in a CI pipeline, so we shouldn't encounter this regression again. I've validated in docker hub and now `latest` and `0.0.20230223` have same tags.
