### ISSUE TITLE
Container crashing since last night

### ISSUE THREAD

**Issue by argium** [masipcat/wireguard-go-docker#35]
I've been using this container for ~3 years no problem. Last night it auto updated and it began to crash repeatedly and could not start.

The error is related to your recent commit which enables this feature by default:
`2024/07/07 11:42:23	stdout	Failed to start server: listen tcp :8080: bind: address already in use`

I'm running this on Synology and use host networking to allow remote client access to other services running on the server so I cannot modify the port number using docker config. Can you please make this feature optional?

**Comment by masipcat** [comment]
Done! Sorry for the inconvenience

**Comment by argium** [comment]
Thank you, and big thank you for maintaining the project over the years. ❤️ It's helped me get around my ISP's CGNAT at one point and I've continued to use it to hide my home IP and access my intranet while travelling.
