### ISSUE TITLE
Resolvconf not found

### ISSUE THREAD

**Issue by citrixscu** [masipcat/wireguard-go-docker#7]
While setting up interface wg0, docker-compose returns with: wireguard_1  | /usr/bin/wg-quick: line 31: resolvconf: command not found. 

wg-quick wg0 up works outside of Docker. Using Arch 5.5.13 w/Mullvad vpn fwiw:

**Comment by masipcat** [comment]
I just pushed the updated docker image. Hope this solve the problem!
