### ISSUE TITLE
arm64/aarch64 docker build?

### ISSUE THREAD

**Issue by adrianmace** [masipcat/wireguard-go-docker#9]
Can you please consider offering an arm64 build within the Docker hub as part of your deployment pipeline to avoid rPi users building themselves?

**Comment by masipcat** [comment]
Sorry for the delay. In the following days, I'll try to investigate how to cross complie and build the images for all archs on travis/github actions

**Comment by masipcat** [comment]
Can you try if `latest` works? I've done a quick test on a raspberry pi but would be awesome if you can test as well :)
